#! /bin/sh


### fix jetbrains ides ###
bspc config focus_follows_pointer false
wmname LG3D

~/.config/polybar/polybar.sh &

feh --randomize --bg-fill ~/Pictures/Wallpaper/

sxhkd &

#### Keyboad Layout Settings
setxkbmap -option grp:alt_shift_toggle us,ir &


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         30

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#d8dee8"
bspc config normal_border_color  "#2f343f"
bspc config presel_feedback_color "#ff5c57"

#Rules
#Terminals
bspc rule -a firefox desktop='^1' focus=on follow=on
bspc rule -a Google-chrome desktop='^1' focus=on follow=on

#Browsers Rule
bspc rule -a Termite desktop='^2' focus=on follow=on

#Editors + IDES
bspc rule -a code-oss desktop='^3' follow=on focus=on
bspc rule -a jetbrains-clion desktop='^3' follow=on focus=on state=floating
bspc rule -a vscodium  desktop='^3' follow=on focus=on
bspc rule -a VSCodium desktop='^3' follow=on focus=on

#File Managers
bspc rule -a dolphin desktop='^4' focus=on follow=on
bspc rule -a Thunar desktop='^4' focus=on follow=on

#Messengers
bspc rule -a TelegramDesktop desktop='^6' focus=on follow=on state=fullscreen
bspc rule -a "discord" desktop='^6' focus=on follow=on

#Documents
bspc rule -a Zathura desktop='^5' focus=on state=tiled follow=on
bspc rule -a okular desktop='^5' focus=on state=fullscreen follow=on

#Media Players
bspc rule -a vlc desktop='^9' follow=on focus=on
bspc rule -a *:Spotify desktop='^9' focus=on follow=on 
bspc rule -a mpv desktop='9'
#bspc rule -a feh state=floating follow=on
#bspc rule -a ffplay state=floating sticky=on

# Compton
if [ -x "$(command -v picom)" ]
then
    killall picom;picom -b --dbus
elif [ -x "$(command -v compton)" ]
then
    killall compton;compton --config ~/.config/compton/compton.conf -b --dbus
fi

# Set Cursor
xsetroot -cursor_name left_ptr

nm-applet &

xautolock -time 10 -corners --00 -detectsleep -locker "~/.config/scripts/lock.sh -s"  -notify 30  -notifier "notify-send -u critical '􀎠 xautolock' 'Suspending in 30 secs...'" &

setxkbmap -option caps:escape
